source 'https://rubygems.org'

gem 'pg'
gem 'rake'
gem 'rack', '~> 1.5'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'

group :test, :development do
  gem 'pry'
end

group :test do
  gem 'rspec'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'poltergeist'
  gem "shoulda"
  gem "shoulda-matchers", "~> 2.4.0", require: false
  gem "valid_attribute"
end
